# Generated by Django 4.2.5 on 2023-09-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locale',
            name='name',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='locale',
            name='timezone',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
