# Generated by Django 4.2.5 on 2023-09-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_locale_name_alter_locale_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locale',
            name='timezone',
            field=models.TextField(blank=True),
        ),
    ]
