# Generated by Django 4.2.5 on 2023-09-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contacts_phones_alter_contacts_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='website',
            field=models.TextField(blank=True),
        ),
    ]
